-- Create product_brands table
CREATE TABLE IF NOT EXISTS product_brands (
    id bigint generated by default as identity primary key,
    name text not null,
    logo_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for product_brands (optional but good practice)
ALTER TABLE product_brands ENABLE ROW LEVEL SECURITY;

-- Add policy for public read access
CREATE POLICY "Public brands are viewable by everyone" ON product_brands
    FOR SELECT USING (true);

-- Add policy for authenticated insert/update/delete (Admin)
CREATE POLICY "Users can insert product_brands" ON product_brands
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update product_brands" ON product_brands
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Users can delete product_brands" ON product_brands
    FOR DELETE USING (auth.role() = 'authenticated');

-- Modify product_collections to reference product_brands
-- First, drop the old text column if it exists (from previous step)
ALTER TABLE product_collections DROP COLUMN IF EXISTS brand;

-- Add the new foreign key column
ALTER TABLE product_collections ADD COLUMN brand_id bigint references product_brands(id);

-- Add index for performance
CREATE INDEX idx_product_collections_brand_id ON product_collections(brand_id);
