-- Create Portfolio Table
CREATE TABLE IF NOT EXISTS portfolio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_th TEXT NOT NULL,
    title_en TEXT,
    description_th TEXT,
    description_en TEXT,
    image_url TEXT,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    comment_th TEXT,
    comment_en TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Promotions Table
CREATE TABLE IF NOT EXISTS promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_th TEXT NOT NULL,
    title_en TEXT,
    description_th TEXT,
    description_en TEXT,
    image_url TEXT,
    start_date DATE,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;

-- Create policies (Adjust based on your auth setup, here allowing public read, admin write)
-- Public Read Access
CREATE POLICY "Public items are visible to everyone" ON portfolio_items FOR SELECT USING (true);
CREATE POLICY "Public reviews are visible to everyone" ON reviews FOR SELECT USING (true);
CREATE POLICY "Public promotions are visible to everyone" ON promotions FOR SELECT USING (true);

-- Admin Write Access (Assuming authenticated users are admins for now, or use specific role)
CREATE POLICY "Authenticated users can insert portfolio" ON portfolio_items FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update portfolio" ON portfolio_items FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete portfolio" ON portfolio_items FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert reviews" ON reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update reviews" ON reviews FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete reviews" ON reviews FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert promotions" ON promotions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update promotions" ON promotions FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete promotions" ON promotions FOR DELETE USING (auth.role() = 'authenticated');
