-- 1. Create Categories Table
CREATE TABLE product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE, -- For URL friendly names if needed
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Collections Table
CREATE TABLE product_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES product_categories(id) ON DELETE CASCADE,
    
    -- Pricing & Unit Info
    unit TEXT NOT NULL, -- e.g., 'm2', 'roll', 'set'
    price_per_unit NUMERIC NOT NULL DEFAULT 0, -- Normal selling price
    price_per_unit_platform NUMERIC DEFAULT 0, -- Platform selling price (optional)
    
    -- Logic
    calculation_method TEXT, -- e.g., 'area_calc', 'box_calc', 'fixed'
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Product Variants/Options (The specific items in a brochure)
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT REFERENCES product_collections(id) ON DELETE CASCADE,
    
    name TEXT NOT NULL, -- e.g., 'Color code 101', 'Pattern A'
    image_url TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;

-- Policies (Public Read, Admin Write)
CREATE POLICY "Public Read Categories" ON product_categories FOR SELECT USING (true);
CREATE POLICY "Public Read Collections" ON product_collections FOR SELECT USING (true);
CREATE POLICY "Public Read Variants" ON product_variants FOR SELECT USING (true);

-- For simplicity in this demo, allow all operations for authenticated users (Admins)
CREATE POLICY "Admin All Categories" ON product_categories FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Collections" ON product_collections FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Variants" ON product_variants FOR ALL USING (auth.role() = 'authenticated');

-- Initial Data Seeding (Optional)
INSERT INTO product_categories (name, slug) VALUES 
('ผ้าม่าน (Curtains)', 'curtains'),
('วอลเปเปอร์ (Wallpaper)', 'wallpaper'),
('มู่ลี่ (Blinds)', 'blinds');
