-- Create quotation_requests table
CREATE TABLE IF NOT EXISTS quotation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    items JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    price_mode TEXT NOT NULL, -- 'shop' or 'platform'
    status TEXT DEFAULT 'pending', -- 'pending', 'contacted', 'completed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for faster sorting/filtering
CREATE INDEX IF NOT EXISTS idx_quotation_requests_created_at ON quotation_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotation_requests_status ON quotation_requests(status);
